CoreNorthWind/CoreNorthWind/Controllers/ProductsController.cs
using CoreNorthWind.Domain.Models;
using CoreNorthWind.Domain.Repositories;
using CoreNorthWind.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace CoreNorthWind.Controllers
{
	[Authorize]
	public class ProductsController : Controller
	{
		private readonly IProductsRepository _productsRepository;
		private readonly ICategoriesRepository _categoriesRepository;
		private readonly ILogger<ProductsController> _logger;
		private readonly int _pageSize;

		private List<Product> _productsList = new List<Product>
		{
			new Product { ProductName = "product 1" },
			new Product { ProductName = "product 2" },
			new Product { ProductName = "product 3" },
			new Product { ProductName = "product 4" }
		};

		public ProductsController(IProductsRepository productsRepository,
			IConfiguration configuration,
			ILogger<ProductsController> logger, ICategoriesRepository categoriesRepository)
		{
			_productsRepository = productsRepository;
			_logger = logger;
			_categoriesRepository = categoriesRepository;
			_pageSize = configuration.GetValue<int>("ProductsPerPage");

			_logger.LogInformation("Products per page value retrieved from configuration: {0}", _pageSize);
		}

		public IActionResult Index(int productPage = 1)
		{
			var productsList = _productsRepository.GetProducts()
				.OrderBy(p => p.ProductID)
				.Skip((productPage - 1) * _pageSize)
				.Take(_pageSize)
				.ToList();

			var productListViewModel = new ProductListViewModel
			{
				Products = productsList,
				PagingInfo = new PagingInfoViewModel
				{
					CurrentPage = productPage,
					ItemsPerPage = _pageSize,
					TotalItems = _productsRepository.GetProducts().Count()
				}
			};

			return View(productListViewModel);
		}

		public IActionResult Add()
		{
			ViewData["Title"] = "Add Product";

			return View("Edit", new ProductEditViewModel());
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Add(ProductEditViewModel productEditViewModel)
		{
			if (ModelState.IsValid)
			{
				_productsRepository.AddProduct(productEditViewModel.Product);

				return RedirectToAction("Index");
			}
			else
			{
				return View("Edit", productEditViewModel);
			}
		}

		public IActionResult Edit(int id)
		{
			var product = _productsRepository.GetProductById(id);
			if (product == null)
			{
				return NotFound();
			}

			ViewData["Title"] = "Edit Product";

			// Create view model
			var viewModel = new ProductEditViewModel
			{
				Product = product,
				Categories = _categoriesRepository.GetCategories().ToList()
			};

			return View("Edit", viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(ProductEditViewModel productEditViewModel)
		{
			if (ModelState.IsValid)
			{
				_productsRepository.UpdateProduct(productEditViewModel.Product);
				return RedirectToAction("Index");
			}

			return View("Edit", productEditViewModel);
		}

		public IActionResult Delete(int id)
		{
			_productsRepository.DeleteProductById(id);

			return RedirectToAction("Index");
		}
	}
}

CoreNorthWind/CoreNorthWind/Controllers/RolesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoreNorthWind.Controllers
{
	[Authorize(Roles = "admin")]
	public class RolesController : Controller
	{
		#region Private Fields

		private readonly RoleManager<IdentityRole> _roleManager;

		#endregion

		#region Constructor

		public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
		{
			_roleManager = roleManager;
		}

		#endregion

		public IActionResult Index() => View(_roleManager.Roles.ToList());

		public IActionResult Create() => View();

		[HttpPost]
		public async Task<IActionResult> Create(string name)
		{
			if (!string.IsNullOrEmpty(name))
			{
				IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
				if (result.Succeeded)
				{
					return RedirectToAction("Index");
				}
				else
				{
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError(string.Empty, error.Description);
					}
				}
			}
			return View(name);
		}

		[HttpPost]
		public async Task<IActionResult> Delete(string id)
		{
			IdentityRole role = await _roleManager.FindByIdAsync(id);
			if (role != null)
			{
				IdentityResult result = await _roleManager.DeleteAsync(role);
			}
			return RedirectToAction("Index");
		}

		public IActionResult UserList() => RedirectToAction("Index", "Users");
	}
}

CoreNorthWind/CoreNorthWind/Views/Shared/_LayoutPrimary.cshtml
@addTagHelper CoreNorthWind.Components.*, CoreNorthWind

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CoreNorthWind</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>

	<environment exclude="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>

	@if (IsSectionDefined("Header"))
	{
		@RenderSection("Header")
	}
	else
	{
		<header>
			<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
				<div class="container">
					<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreNorthWind</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</header>
	}

	<div class="container">
		<main role="main" class="pb-3">
			<div>
				@await Component.InvokeAsync("Breadcrumbs", new { delimiter = ">" })
			</div>
			@RenderBody()
		</main>
	</div>

	@if (IsSectionDefined("Footer"))
	{
		@RenderSection("Footer")
	}
	else
	{
		<footer class="border-top footer text-muted">
			<div class="container">
				&copy; 2020 - SK CoreNorthWind - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
			</div>

		</footer>
	}

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

CoreNorthWind/CoreNorthWind/Views/Shared/_LayoutSecondary.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CoreNorthWind</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>

	<environment exclude="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body style="margin-bottom: 0 !important">

	<div class="masthead">
		<div class="container h-100">
			<div class="row h-100 align-items-center justify-content-center text-center">
				<div class="col-lg-10 align-self-end">
					<h1 class="text-uppercase text-white font-weight-bold">Welcome</h1>
					<hr class="divider my-4" />
				</div>
				<div class="col-lg-8 align-self-baseline">
					<p class="text-white-75 font-weight-light mb-5">Start exploring CoreNorthWind with Products and Categories. Enjoy the design and technical excellence!</p>
					<div class="container">
						<main role="main" class="pb-3">
							@RenderBody()
						</main>
					</div>
					@if (User.Identity.IsAuthenticated)
					{
						<div class="fixed-bottom">
							<p class="text-white-75 font-weight-light mb-5">
								You are logged as @User.Identity.Name
							</p>

							<p>
								@if (User.IsInRole("admin"))
								{
									<a asp-controller="Users" asp-action="Index" class="btn btn-outline-light">Manage Users</a>
									<a asp-controller="Roles" asp-action="Index" class="btn btn-outline-light">Manage Roles</a>
								}
								<a asp-controller="Account" asp-action="Logout" class="btn btn-outline-light">Logout</a>
							</p>
						</div>
					}
				</div>
			</div>
		</div>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>